CREATE TABLE IF NOT EXISTS public."USUARIO"
(
	"Email" CHAR(50) UNIQUE NOT NULL,
	"Nome" VARCHAR(100) NOT NULL,
	"Hash" VARCHAR(250) UNIQUE NOT NULL,
	"Token" VARCHAR(250) UNIQUE,
	"Token_validade" TIMESTAMP,
	 PRIMARY KEY ("Email")
);


CREATE TABLE IF NOT EXISTS public."POST" 
(
  "Id" SERIAL UNIQUE NOT NULL,
  "Usuario_email" CHAR(50) NOT NULL,
  "Answer_to" INT NULL,
  "Texto" VARCHAR(500) NOT NULL,
  PRIMARY KEY ("Id", "Usuario_email"),
  CONSTRAINT "FK_POST_USUARIO"
    FOREIGN KEY ("Usuario_email")
    REFERENCES public."USUARIO" ("Email")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "FK_POST_POST"
    FOREIGN KEY ("Answer_to")
    REFERENCES public."POST" ("Id")
    ON DELETE SET NULL
    ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS public."FAQ" 
(
  "Id" SERIAL UNIQUE NOT NULL,
  "Pergunta" VARCHAR(200) NOT NULL,
  "Resposta" VARCHAR(400) NOT NULL,
  PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS public."POST_AVALIACAO" 
(
  "Usuario_email" CHAR(50) UNIQUE NOT NULL,
  "Post_id" INT NOT NULL,
  "Nota" INT NOT NULL,
  PRIMARY KEY ("Usuario_email", "Post_id"),
  CONSTRAINT "FK_POST_AVALIACAO_USUARIO"
    FOREIGN KEY ("Usuario_email")
    REFERENCES public."USUARIO" ("Email")
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT "FK_POST_AVALIACAO_POST"
    FOREIGN KEY ("Post_id")
    REFERENCES public."POST" ("Id")
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);